version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_USER: usercs
      POSTGRES_PASSWORD: password
      POSTGRES_DB: InsectPlatformDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./images:/images
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - my_network
    restart: always
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5050:80"  # Access pgAdmin via http://<server-ip>:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - my_network
    depends_on:
      - postgres
    restart: always

volumes:
  db_data:
  pgadmin_data:

networks:
  my_network:
    driver: bridge